steps:
  # ── Phase 1: Build both images in parallel ───────────────

  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_REPO}/backend:${SHORT_SHA}
      - -t
      - ${_AR_REPO}/backend:latest
      - ./backend
    waitFor: ["-"]

  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_URL=${_BACKEND_URL}
      - -t
      - ${_AR_REPO}/frontend:${SHORT_SHA}
      - -t
      - ${_AR_REPO}/frontend:latest
      - ./frontend
    waitFor: ["-"]

  # ── Phase 2: Push both images in parallel ────────────────

  - id: push-backend
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, "${_AR_REPO}/backend"]
    waitFor: [build-backend]

  - id: push-frontend
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, "${_AR_REPO}/frontend"]
    waitFor: [build-frontend]

  # ── Phase 3: Deploy both services in parallel ────────────

  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image=${_AR_REPO}/backend:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8000
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --set-secrets=DATABASE_URL=${_DB_SECRET}:latest
      - --set-env-vars=CORS_ORIGINS=${_CORS_ORIGINS}
      - --network=default
      - --subnet=default
      - --vpc-egress=private-ranges-only
      - --add-cloudsql-instances=${_CLOUD_SQL_CONNECTION}
    waitFor: [push-backend]

  - id: deploy-frontend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_FRONTEND_SERVICE}
      - --image=${_AR_REPO}/frontend:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      - --memory=256Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
    waitFor: [push-frontend]

substitutions:
  _AR_REPO: europe-west1-docker.pkg.dev/personal-cloud-42/elec-night
  _REGION: europe-west1
  _BACKEND_SERVICE: election-backend
  _FRONTEND_SERVICE: election-frontend
  _BACKEND_URL: https://election-backend-247697904207.europe-west1.run.app
  _DB_SECRET: election-db-url
  _CLOUD_SQL_CONNECTION: personal-cloud-42:europe-west1:election-night-instance
  _CORS_ORIGINS: '["https://election-frontend-247697904207.europe-west1.run.app"]'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - ${_AR_REPO}/backend:${SHORT_SHA}
  - ${_AR_REPO}/backend:latest
  - ${_AR_REPO}/frontend:${SHORT_SHA}
  - ${_AR_REPO}/frontend:latest
